# Generated by Django 3.0.8 on 2020-08-06 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=100)),
                ('apellidoCliente', models.CharField(max_length=100)),
                ('correoCliente', models.EmailField(max_length=254)),
                ('telefonoCliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=100)),
                ('imagenProducto', models.ImageField(upload_to='pics')),
                ('precioProducto', models.IntegerField()),
                ('ofertaProducto', models.BooleanField(default=False)),
                ('precioOfertaProducto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVenta', models.DateTimeField(verbose_name='data published')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.Cliente')),
                ('detalleVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.DetalleVenta')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimarket.Producto'),
        ),
    ]
